apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: friday
resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - api-deployment.yaml
  - engine-deployment.yaml
  - dashboard-deployment.yaml
  - services.yaml
  - ingress.yaml
