apiVersion: v1
kind: Service
metadata:
  name: friday-api
spec:
  selector:
    app: friday-api
  ports:
    - name: http
      port: 8000
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: friday-dashboard
spec:
  selector:
    app: friday-dashboard
  ports:
    - name: http
      port: 80
      targetPort: http
