{{- if .Values.dashboard.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "friday.fullname" . }}-dashboard
  labels:
    {{- include "friday.labels" . | nindent 4 }}
  {{- with .Values.dashboard.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.dashboard.ingress.className }}
  ingressClassName: {{ .Values.dashboard.ingress.className }}
  {{- end }}
  rules:
    {{- range .Values.dashboard.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "friday.fullname" $ }}-dashboard
                port:
                  number: {{ $.Values.dashboard.service.port }}
          {{- end }}
    {{- end }}
  {{- with .Values.dashboard.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
