apiVersion: v1
kind: Service
metadata:
  name: {{ include "friday.fullname" . }}-api
  labels:
    {{- include "friday.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "friday.fullname" . }}-dashboard
  labels:
    {{- include "friday.labels" . | nindent 4 }}
spec:
  type: {{ .Values.dashboard.service.type }}
  selector:
    app.kubernetes.io/component: dashboard
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.dashboard.service.port }}
      targetPort: http
